"""add language to posts

Revision ID: 94651bb04da3
Revises: ec691f45cd00
Create Date: 2018-07-19 06:46:57.257609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94651bb04da3'
down_revision = 'ec691f45cd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
